#!/usr/bin/env -S buildah unshare ansible-playbook
---
- name: Create Galaxy Application Container
  hosts: buildah_server
  gather_facts: false
  vars_files: [vars.yml]
  roles:
  - role: new_container
    vars:
      name: "{{ containers.app.name }}"
      base_image: python:slim
      cmd: 'uwsgi --yaml {{ paths.config }}/galaxy.yml --uid={{ uwsgi.uid }} --gid={{ uwsgi.gid }}'

- name: Configure Container Environment
  hosts: "{{ containers.app.name }}"
  gather_facts: false
  vars_files: [vars.yml]
  roles: [galaxy_env, galaxy_app, galaxy_docker, galaxy_k8s, galaxy_text_tools]

- name: Finish Galaxy Application Container
  hosts: buildah_server
  gather_facts: false
  vars_files: [vars.yml]
  tasks:
  - name: Commit container
    command: buildah commit {{ hostvars[containers.app.name]['ansible_host'] }} {{ containers.app.name }}
