---
- name: Create Galaxy Application Container
  hosts: buildah_server
  vars_files: [vars.yml]
  tasks:
    - name: Create container
      command: buildah from alpine
      register: container_handle

    - debug:
        var: container_handle.stdout

    - name: Configure container
      # TODO - healthcheck command
      command: >-
        buildah config
        --author "{{ author }}"
        --cmd 'uwsgi --yaml {{ GALAXY_ROOT }}/config/galaxy.yml'
        --env GALAXY_ROOT={{ GALAXY_ROOT }}
        {{ container_handle.stdout }}

    - name: Populate container
      command: buildah copy {{ container_handle.stdout }} '{{ playbook_dir }}/{{ item.from }}' '{{ GALAXY_ROOT }}/{{ item.to }}'
      loop:
      - {from: galaxy/requirements.txt, to: requirements.txt}
      - {from: galaxy/lib, to: lib}
      - {from: galaxy/locale, to: locale}
      - {from: galaxy/templates, to: templates}
      - {from: config/, to: config/}

    - name: Add Podman container to inventory
      add_host:
        name: galaxy_app
        ansible_connection: buildah
        remote_user: root
        ansible_host: "{{ container_handle.stdout }}"
        remote_tmp: "{{ tmp_path }}/.ansible/"

- name: Configure Container Environment
  hosts: galaxy_app
  gather_facts: false
  vars_files: [vars.yml]
  vars:
    roles: []
  tasks:
    - name: Install system dependencies
      raw: apk {{ item }}
      loop:
      - update
      - add python3
      - add --virtual build-dependencies -X http://dl-cdn.alpinelinux.org/alpine/edge/testing hdf5-dev py3-setuptools build-base gcc linux-headers musl-dev python3-dev libffi-dev zlib-dev bzip2-dev xz-dev openssl-dev libxml2-dev libxslt-dev

    - name: Install python dependencies
      command: pip3 install -r $GALAXY_ROOT/requirements.txt --index-url https://wheels.galaxyproject.org/simple --extra-index-url https://pypi.python.org/simple --no-cache-dir

    - name: Clean up
      command: apk del build-dependencies

    - name: Execute roles
      include_role:
        name: "{{ item }}"
      loop: "{{ roles }}"

- name: Finish Galaxy Application Container
  hosts: buildah_server
  tasks:
    - name: Commit container
      command: buildah commit {{ container_handle.stdout }} {{ containers.app.name }}
