#!/usr/bin/env -S buildah unshare ansible-playbook
---
- name: Create Galaxy Worker Container
  hosts: buildah_server
  vars_files: [vars.yml]
  tasks:
    - name: Create container
      command: buildah from {{ containers.app.name }}
      register: container_handle

    - debug:
        var: container_handle.stdout

    - name: Configure container
      # TODO - healthcheck command
      # https://docs.galaxyproject.org/en/master/admin/scaling.html#uwsgi-for-web-serving-and-webless-galaxy-applications-as-job-handlers
      command: >-
        buildah config
        --cmd 'python {{ galaxy.paths.root }}/scripts/galaxy-main -c {{ galaxy.paths.config }}/galaxy.yml --server-name=$HOSTNAME --log-file=/dev/stdout'
        {{ container_handle.stdout }}

    - name: Commit container
      command: buildah commit {{ container_handle.stdout }} {{ containers.worker.name }}