---
- name: Create container
  command: buildah from {{ base_image }}
  register: container_handle

- debug:
    var: container_handle.stdout

- name: Configure container
  command: >-
    buildah config
    --author "{{ author }}"
    {% if entrypoint is defined %}
    --entrypoint '{{ entrypoint }}'
    {% endif %}
    {% if cmd is defined %}
    --cmd '{{ cmd }}'
    {% endif %}
    {% if user is defined %}
    --user '{{ user }}'
    {% endif %}
    {% if envs is defined %}
    {% for k, v in envs.items() %}
    --env {{ k }}={{ v }}
    {% endfor %}
    {% endif %}
    {{ container_handle.stdout }}

- name: Add application container to inventory
  ansible.builtin.add_host:
    name: '{{ name }}'
    ansible_connection: containers.podman.buildah
    remote_user: '{{ build_user }}'
    ansible_host: "{{ container_handle.stdout }}"