---
- name: galaxy.yml
  template:
    src: galaxy.yml.j2
    dest: "{{ paths.config }}/galaxy.yml"
    mode: u=rw,g=r,o=r

- name: gunicorn.yml
  template:
    src: gunicorn.yml.j2
    dest: "{{ paths.config }}/gunicorn.yml"
    mode: u=rw,g=r,o=r