---
- name: Touch job_conf.xml
  file:
    state: touch
    mode: u=rw,g=r,o=r
    path: "{{ galaxy.paths.config }}/job_conf.xml"

- name: Add properties for plugins
  xml:
    xpath: /job_conf/{{ item }}
    path: "{{ galaxy.paths.config }}/job_conf.xml"
  loop: "{{ galaxy.config.job_conf.defaults.plugins }}"