---
- name: Ensure config dir exists
  file:
    path: '{{ galaxy_config }}'
    recurse: yes
    state: directory

- name: Ensure data dir exists with permissions
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
    owner: '{{ app.user }}'
    group: '{{ app.group }}'
    mode: ugo+rw
  loop:
    - '{{ paths.data }}'
    - '{{ paths.managed_config }}'

# Don't use copy as it is very very slow when copying lots of files
- name: Populate container
  command: buildah copy {{ hostvars[containers.app.name]['ansible_host'] }} '{{ playbook_dir }}/{{ item.from }}' '{{ paths.root }}/{{ item.to }}'
  delegate_to: buildah_server
  loop:
  - {from: galaxy/lib, to: lib}
  - {from: galaxy/templates, to: templates}
  - {from: galaxy/scripts, to: scripts}
  - {from: galaxy/tools, to: tools}

# TODO replace sample configs with galaxy.config.* data structures and templates like tool_conf.yml
- name: Copy in sample configs and additional files
  copy:
    src: '{{ item.from }}'
    dest: '{{ item.to }}'
    local_follow: yes
  loop:
  - {from: '{{ playbook_dir }}/galaxy/config/datatypes_conf.xml.sample', to: "{{ paths.config }}/datatypes_conf.xml" }
  - {from: '{{ playbook_dir }}/galaxy/config/workflow_schedulers_conf.xml.sample', to: "{{ paths.config }}/workflow_schedulers_conf.xml" }
  - {from: 'container_resolvers_conf.yml', to: "{{ paths.config }}/container_resolvers_conf.yml" }
  - {from: 'tool_data_table_conf.xml', to: "{{ paths.config }}/tool_data_table_conf.xml" }
  - {from: 'gunicorn.conf.py', to: "{{ paths.config }}/gunicorn.conf.py" }
  - {from: 'create_db.sh', to: "{{ paths.root }}/create_db.sh" }
  - {from: 'create_toolshed_db.sh', to: "{{ paths.root }}/create_toolshed_db.sh" }
  - {from: 'manage_db.sh', to: "{{ paths.root }}/manage_db.sh" }
  - {from: 'run_alembic.sh', to: "{{ paths.root }}/run_alembic.sh" }
  - {from: 'run_reports.sh', to: "{{ paths.root }}/run_reports.sh" }
  - {from: 'run_tool_shed.sh', to: "{{ paths.root }}/run_tool_shed.sh" }
  - {from: 'run.sh', to: "{{ paths.root }}/run.sh" }  # Required by galaxy-main script to simply exist
  - {from: 'navigation.yml', to: "{{ paths.root }}/lib/galaxy/selenium/navigation.yml" }  # Required by galaxy tour

- import_tasks: galaxy.yml
- import_tasks: job_conf.yml
- import_tasks: tool_conf.yml