---
- import_tasks: nginx.yml

- name: Add group
  group:
    name: '{{ app.group }}'
    gid: '{{ app.gid }}'

- name: Add user
  user:
    name: '{{ app.user }}'
    group: '{{ app.group }}'
    uid: '{{ app.uid }}'
    shell: /sbin/nologin

- name: Populate container
  command: buildah copy {{ hostvars[containers.web.name]['ansible_host'] }} '{{ playbook_dir }}/{{ item.from }}' '{{ item.to }}'
  delegate_to: buildah_server
  loop:
    - {from: galaxy/static, to: '{{ nginx.paths.root }}'}

- name: Use default welcome
  file:
    path: '{{ nginx.paths.root }}/welcome.html'
    src: welcome.html.sample
    state: link