---
- import_tasks: nginx.yml

- name: Use default welcome
  file:
    path: '{{ nginx.paths.root }}/welcome.html'
    src: welcome.html.sample
    state: link

- name: Add group
  group:
    name: galaxy
    gid: 1000

- name: Add user
  user:
    name: galaxy
    group: galaxy
    uid: 1000
    shell: /sbin/nologin