---
- import_tasks: nginx.yml

- name: Add group
  group:
    name: galaxy
    gid: 1000

- name: Add user
  user:
    name: galaxy
    group: galaxy
    uid: 1000
    shell: /sbin/nologin

- name: Populate container
  command: buildah copy {{ hostvars[containers.web.name]['ansible_host'] }} '{{ playbook_dir }}/{{ item.from }}' '{{ item.to }}'
  delegate_to: buildah_server
  loop:
    - {from: galaxy/static, to: '{{ nginx.paths.root }}'}

- name: Use default welcome
  file:
    path: '{{ nginx.paths.root }}/welcome.html'
    src: welcome.html.sample
    state: link