---
- name: Copy in files
  copy:
    src: '{{ item.from }}'
    dest: '{{ item.to }}'
    mode: preserve
  loop:
    - {from: nginx.conf, to: /etc/nginx/ }
    - {from: cors.conf, to: /etc/nginx/ }
    - {from: cors_options.conf, to: /etc/nginx/ }
    - {from: entry.sh, to: / }

- name: Remove base image custom config
  file:
    path: '{{ item }}'
    state: absent
  loop:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/nginx_upload.default.conf

- name: Generate galaxy.nginx.conf
  template:
    src: "galaxy.nginx.conf.j2"
    dest: "{{ nginx.paths.config }}/galaxy.conf"
    mode: u=rw,g=r,o=r