---
galaxy:
  config:
    job_conf:
      default_workers: 4
      default_destination: default
      handler_assign_with:
      #  - mem-self	# In-memory Self Assignment
      #  - db-self	# Database Self Assignment
      #  - db-preassign	# Database Preassignment
      #  - uwsgi-mule-message	# uWSGI Mule Messaging
      #  - db-transaction-isolation	# Database Transaction Isolation
        - db-skip-locked	# Database SKIP LOCKED
      #  handler_max_grab:
      #  default_handler:
      #  default_destination: local
      plugins:
        local:
          type: runner
          load: galaxy.jobs.runners.local:LocalJobRunner
      handlers: {}
      #  id:
      #    tags: []
      #    plugins: []
      destinations:
        local:
          runner: local
      #    params:
      #      param: val
      #      container: {type: image: shell="/bin/sh" resolve_dependencies="false" }
      #      container_override: {type: image: shell="/bin/sh" resolve_dependencies="false" }
      #    job_metrics: {}
      #    env: {}
      #    source: ['path',]
      #    exec: ['cmd',]
      #    resubmit: [{condition: "", destination: "", handler: ""}]
      tools:
        upload1:
          destination: local
        unzip:
          destination: local
        zip:
          destination: local
        failed:
          destination: local
        flatten:
          destination: local
        merge:
          destination: local
        relabel:
          destination: local
        filter:
          destination: local
        sort:
          destination: local
        apply_rules:
          destination: local
      limits: {}