---
galaxy:
  config:
    job_conf:
      oversubscribe_factor: 2
      job_profiles:
        tiny:
          cpu: 0.5
          memory: 0.5
        c1m1: &default
          cpu: 1
          memory: 1
        c1m2:
          cpu: 1
          memory: 1
        c2m2:
          cpu: 2
          memory: 2
        c2m4:
          cpu: 2
          memory: 4
        c4m8:
          cpu: 4
          memory: 8
        c8m16:
          cpu: 8
          memory: 16
        c16m32:
          cpu: 16
          memory: 32
        default: *default
      default_workers: 4
      default_destination: default
      handler_assign_with:
      #  - mem-self	# In-memory Self Assignment
      #  - db-self	# Database Self Assignment
      #  - db-preassign	# Database Preassignment
      #  - uwsgi-mule-message	# uWSGI Mule Messaging
      #  - db-transaction-isolation	# Database Transaction Isolation
        - db-skip-locked	# Database SKIP LOCKED
      #  handler_max_grab:
      #  default_handler:
      #  default_destination: local
      plugins:
        local:
          type: runner
          load: galaxy.jobs.runners.local:LocalJobRunner
      handlers: {}
      #  id:
      #    tags: []
      #    plugins: []
      destinations:
        local:
          profiles: [tiny]
          runner: local
      #    params:
      #      param: val
      #      container: {type: image: shell="/bin/sh" resolve_dependencies="false" }
      #      container_override: {type: image: shell="/bin/sh" resolve_dependencies="false" }
      #    job_metrics: {}
      #    env: {}
      #    source: ['path',]
      #    exec: ['cmd',]
      #    resubmit: [{condition: "", destination: "", handler: ""}]
      tools:
        upload1:
          destination: local-tiny
        unzip:
          destination: local-tiny
        zip:
          destination: local-tiny
        failed:
          destination: local-tiny
        flatten:
          destination: local-tiny
        merge:
          destination: local-tiny
        relabel:
          destination: local-tiny
        filter:
          destination: local-tiny
        sort:
          destination: local-tiny
        apply_rules:
          destination: local-tiny
      limits: {}