---
galaxy:
  config:
    job_conf:
      defaults:
        plugins:
          workers: 4
        #handlers:
        #  assign_with:
        #    - mem-self	# In-memory Self Assignment
        #    - db-self	# Database Self Assignment
        #    - db-preassign	# Database Preassignment
        #    - uwsgi-mule-message	# uWSGI Mule Messaging
        #    - db-transaction-isolation	# Database Transaction Isolation
        #    - db-skip-locked	# Database SKIP LOCKED
        #  max_grab:
        #  default:
        destinations:
          default: local
      plugins:
        local:
          type: runner
          load: galaxy.jobs.runners.local:LocalJobRunner
      handlers: {}
      #  - id:
      #    plugins:
      #      -
      destinations:
        local:
          runner: local
      #    params:
      #    job_metrics:
      tools: {}
      limits: {}