uwsgi:
  http: 127.0.0.1:9087
  buffer-size: 16384
  processes: 1
  threads: 4
  offload-threads: 2
  static-map: /static/style=static/style/blue
  static-map: /static=static
  static-map: /favicon.ico=static/favicon.ico
  master: true 
  virtualenv: venv
  pythonpath: lib
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  manage-script-name: false
  thunder-lock: true 
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true
galaxy:
  database_connection: sqlite:///$GALAXY_ROOT/universe.sqlite?isolation_level=IMMEDIATE
  job_config_file: $GALAXY_CONFIG/job_conf.xml
  file_path: $GALAXY_DATA/database/files
  new_file_path: $GALAXY_DATA/database/tmp
  tool_config_file: $GALAXY_CONFIG/tool_conf.xml
  shed_tool_config_file: $GALAXY_CONFIG/shed_tool_conf.xml
  tool_dependency_dir: $GALAXY_DATA/tool-deps
  tool_data_table_config_path: $GALAXY_CONFIG/tool_data_table_conf.xml
  visualization_plugins_directory: $GALAXY_ROOT/visualizations
  datatypes_config_file: $GALAXY_CONFIG/datatypes_conf.xml
  watch_tools: 'true'
  legacy_eager_objectstore_initialization: true 
  builds_file_path: $GALAXY_DATA/builds.txt
  job_working_directory: $GALAXY_DATA/database/jobs_directory
  cluster_files_directory: $GALAXY_DATA/database/slurm
  template_cache_path: $GALAXY_DATA/database/compiled_templates
  citation_cache_data_dir: $GALAXY_DATA/database/citations/data
  citation_cache_lock_dir: $GALAXY_DATA/database/citations/lock
  brand: $GALAXY_BRAND
  #pretty_datetime_format: $iso8601
  #remote_user_maildomain: 'external.ca'
  #remote_user_secret:
  #single_user:
  admin_users: $GALAXY_ADMIN_USERS
  allow_user_deletion: True
  allow_user_impersonation: True
  master_api_key: $GALAXY_MASTER_API_KEY
  cleanup_job: always
