---
galaxy:
  config:
    job_conf:
      destinations:
        docker: &docker
          runner: local
          tags: default
          params: &docker_params
            enabled:
              default: False
              from_environ: DOCKER_ENABLED
            docker_enabled: true
            require_container: true
            embed_metadata_in_job: true
            docker_host: 'unix:///var/run/docker.sock'
            docker_sudo: false
            docker_default_container_id:
              from_environ: DEFAULT_CONTAINER_ID
              default: '{{ containers.worker.name }}'
            #docker_volumes: '{{ volumes.galaxy_root.name }}:$galaxy_root:ro,{{ volumes.user_data.name }}:$tool_directory:ro,{{ volumes.user_data.name }}:$job_directory:ro,$working_directory:rw,{{ volumes.user_data.name }}:$default_file_path:ro'
            docker_volumes:
              from_environ: DOCKER_VOLUME_MOUNTS
              default: '{{ volumes.galaxy_root.name }}:$galaxy_root:ro,{{ volumes.user_data.name }}:/data:rw,$working_directory:rw'
            docker_auto_rm: true
            #docker_set_user: '$UID'
        galaxy_env:
          <<: *docker
          params:
            <<: *docker_params
            docker_run_extra_arguments: '--entrypoint="/env_run.sh" -e "PYTHONPATH={{ paths.root }}/lib"'
